### ISSUE TITLE
Suggestions to improve this website.

### ISSUE THREAD

**Issue by Raj2032** [learning-rust/learning-rust.github.io#22]
I like how it is well polished. However I wish there it was more interactive, like CodeCadmey and Khan Academy.

Take a look at how it explains how to do programming
https://www.khanacademy.org/computing/computer-programming/programming/drawing-basics/pt/drawing-more-shapes-with-code

In this link, it is an interactive video, meaning that you can change code inside the video so you can experiment.

https://www.khanacademy.org/computing/computer-programming/programming/drawing-basics/pc/challenge-simple-snowman
In this link I like how they give you an interactive exercise, and I wish to see that in Rust as well.

**Comment by dumindu** [comment]
Thanks for your feedback. But, this is out of scope, especially using videos inside doc. That approach will be good for small video tutorial series but will not suitable for a language with comparatively large learning curve and new concepts. Especially because when using videos, user has to spend more time compared to docs. 
 
However I have some plans for "After Doc"/"exercise" sections for long time, but unfortunately I am bit unstable/unable to continuously invest more time on Rust each day even I love it , due to working env and personal matters in this year. But I am pretty sure more things will be added around end of this year/ in the beginning of next year.

Won't fix! Out Of Scope!
