### ISSUE TITLE
Just wanted to say a big thank you for creating this site.

### ISSUE THREAD

**Issue by Annis-Monadjem** [learning-rust/learning-rust.github.io#43]
Just wanted to say a big thank you for creating this site.

**Comment by dumindu** [comment]
Hi @Annis-Monadjem ,
Thanks and I am glad it helped you and sorry for not keep updating this site due to I am more active with Go, K8s and Istio stuff with my career life these days. With Rust Edition 2018, we got some simplified syntax for some areas but some pages are not having those changes for the moment. So, If you found any missing point or anything need to be added, feel free to comment, create a PR or buzz me in here or Reddit /u/dumindunuwan. 
Thanks
