### ISSUE TITLE
Numbered chapters for quick reference

### ISSUE THREAD

**Issue by k12ish** [learning-rust/learning-rust.github.io#51]
In many situations, it is useful to refer to chapters by number. eg. Chapter 3.1

**Comment by dumindu** [comment]
@k12ish 
- I don't see any benefit of this for web urls. 
- Btw I am considering [Hugo](https://gohugo.io/) these days due to the issues I faced with Node ecosystem past years. **May be** I will move this project to Hugo after some time. And there, I am using `/docs/section-01/article-01` url pattern.

<img width="440" alt="Screenshot 2021-01-03 at 1 24 56 AM" src="https://user-images.githubusercontent.com/1280428/103462835-f6579200-4d62-11eb-8d78-54d2011a8198.png">
 
 However, I believe article title should be unique and should focus on that.
